name: 'Get user that pushes commit'
description: 'Greet someone and record the time'

outputs:
  pusher: # id of output
    description: 'Who pushed commit'
runs:
  using: 'node12'
  main: 'index.js'
